class_names:
- Keep left
- Keep right
- No U-turn
- No left turn
- No parking
- No right turn
- No stopping
- Parking
- Pedestrian Crossing
- Speed Limit -100-
- Speed Limit -30-
- Speed Limit -60-
- Stop Sign
- Traffic Light -Green-
- Traffic Light -Red-
- Traffic Light -Yellow-
- U-turn
- bike
- motobike
- person
- vehicle
data:
  train:
    ann_path: /home/newin/Projects/nanodet_sign/Nano_sign/coco_annotation/instances_train.json
    img_path: /home/newin/Projects/nanodet_sign/Nano_sign/yolodark_nano_dataset/train/images
    input_size:
    - 416
    - 416
    keep_ratio: false
    name: CocoDataset
    pipeline:
      brightness: 0.2
      contrast:
      - 0.6
      - 1.4
      flip: 0.5
      normalize:
      - - 103.53
        - 116.28
        - 123.675
      - - 57.375
        - 57.12
        - 58.395
      perspective: 0.0
      rotation: 0
      saturation:
      - 0.5
      - 1.2
      scale:
      - 0.6
      - 1.4
      shear: 0
      stretch:
      - - 0.8
        - 1.2
      - - 0.8
        - 1.2
      translate: 0.2
  val:
    ann_path: /home/newin/Projects/nanodet_sign/Nano_sign/coco_annotation/instances_valid.json
    img_path: /home/newin/Projects/nanodet_sign/Nano_sign/yolodark_nano_dataset/valid/images
    input_size:
    - 416
    - 416
    keep_ratio: false
    name: CocoDataset
    pipeline:
      normalize:
      - - 103.53
        - 116.28
        - 123.675
      - - 57.375
        - 57.12
        - 58.395
device:
  batchsize_per_gpu: 8
  gpu_ids:
  - 0
  precision: 32
  workers_per_gpu: 6
evaluator:
  name: CocoDetectionEvaluator
  save_key: mAP
grad_clip: 35
log:
  interval: 50
model:
  arch:
    aux_head:
      activation: LeakyReLU
      feat_channels: 192
      input_channel: 192
      name: SimpleConvHead
      num_classes: 21
      reg_max: 7
      stacked_convs: 4
      strides:
      - 8
      - 16
      - 32
      - 64
    backbone:
      activation: LeakyReLU
      model_size: 1.0x
      name: ShuffleNetV2
      out_stages:
      - 2
      - 3
      - 4
    detach_epoch: 10
    fpn:
      activation: LeakyReLU
      in_channels:
      - 116
      - 232
      - 464
      kernel_size: 5
      name: GhostPAN
      num_extra_level: 1
      out_channels: 96
      use_depthwise: true
    head:
      activation: LeakyReLU
      feat_channels: 96
      input_channel: 96
      kernel_size: 5
      loss:
        loss_bbox:
          loss_weight: 2.0
          name: GIoULoss
        loss_dfl:
          loss_weight: 0.25
          name: DistributionFocalLoss
        loss_qfl:
          beta: 2.0
          loss_weight: 1.0
          name: QualityFocalLoss
          use_sigmoid: true
      name: NanoDetPlusHead
      norm_cfg:
        type: BN
      num_classes: 21
      reg_max: 7
      stacked_convs: 2
      strides:
      - 8
      - 16
      - 32
      - 64
    name: NanoDetPlus
  weight_averager:
    decay: 0.9998
    name: ExpMovingAverager
save_dir: /home/newin/Projects/nanodet_sign/workspace/traffic_sign
schedule:
  lr_schedule:
    T_max: 50
    eta_min: 5.0e-05
    name: CosineAnnealingLR
  optimizer:
    lr: 0.001
    name: AdamW
    weight_decay: 0.05
  total_epochs: 150
  val_intervals: 10
  warmup:
    name: linear
    ratio: 0.0001
    steps: 500
test: {}
